TicketDesk.Web.Client/Controllers/AutoCompleteController.cs
// TicketDesk - Attribution notice
// Contributor(s):
//
//      Stephen Redd (https://github.com/stephenredd)
//
// This file is distributed under the terms of the Microsoft Public 
// License (Ms-PL). See http://opensource.org/licenses/MS-PL
// for the complete terms of use. 
//
// For any distribution that contains code from this file, this notice of 
// attribution must remain intact, and a copy of the license must be 
// provided to the recipient.

using System.Linq;
using System.Web.Mvc;
using TicketDesk.Domain;

namespace TicketDesk.Web.Client.Controllers
{
    [RoutePrefix("auto-complete")]
    [TdAuthorize(Roles = "TdInternalUsers,TdHelpDeskUsers,TdAdministrators")]
    public class AutoCompleteController : Controller
    {

        private TdDomainContext Context { get; set; }
        public AutoCompleteController(TdDomainContext context)
        {
            Context = context;
        }

        [Route("tag-list")]
        [HttpGet]
        public ActionResult TagList(string term)
        {
            //TODO: cache a complete distinct taglist on app start to improve performance, keep this action synchronous
            var tags = Context.TicketTags
                        .Where(tag => tag.TagName.StartsWith(term))
                        .GroupBy(tag => tag.TagName)
                        .Select(g => g.FirstOrDefault())
                        .Take(10);//limit to 10

            //pull data, then convert to format expected by select2
            return new JsonCamelCaseResult
            {
                Data = tags.ToArray().Select(t => new {Id = t.TagName, Text = t.TagName}),
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }
    }
}

TicketDesk.Web.Client/Controllers/FileController.cs
// TicketDesk - Attribution notice
// Contributor(s):
//
//      Stephen Redd (https://github.com/stephenredd)
//
// This file is distributed under the terms of the Microsoft Public 
// License (Ms-PL). See http://opensource.org/licenses/MS-PL
// for the complete terms of use. 
//
// For any distribution that contains code from this file, this notice of 
// attribution must remain intact, and a copy of the license must be 
// provided to the recipient.

using System;
using System.Configuration;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using TicketDesk.IO;

namespace TicketDesk.Web.Client.Controllers
{
    [RoutePrefix("file")]
    [TdAuthorize(Roles = "TdInternalUsers,TdHelpDeskUsers,TdAdministrators")]
    public class FileController : Controller
    {
        [HttpPost]
        [Route("upload")]
        public async Task<ActionResult> Upload(Guid tempId)
        {
            var demoMode = (ConfigurationManager.AppSettings["ticketdesk:DemoModeEnabled"] ?? "false").Equals("true", StringComparison.InvariantCultureIgnoreCase);
            if (demoMode)
            {
                return new EmptyResult();
            }
            //TODO: doesn't necessarily play well with large files, cap file upload size to something reasonable (define in settings) or use upload chunking
            foreach (string fileName in Request.Files)
            {
                var file = Request.Files[fileName];
                Debug.Assert(file != null, "file != null");
                
                await TicketDeskFileStore.SaveAttachmentAsync(file.InputStream, file.FileName, tempId.ToString(), true);
            }
            return new JsonCamelCaseResult { Data = new { Message = string.Empty } };//dropzone expects a message property back
        }

        [HttpPost]
        [Route("delete")]
        public JsonResult Delete(Guid id, string fileName)
        {
            //ticketdesk never lets the UI directly delete a file attachment unless it is a pending. 
            TicketDeskFileStore.DeleteAttachment(fileName, id.ToString(), true);
            return new JsonCamelCaseResult { Data = new { Message = string.Empty } };//dropzone expects a message property back
        }

        [HttpGet]
        [Route("{id}/{fileName}", Name = "GetAttachedFile")]
        public ActionResult GetFile(string id, string fileName)
        {
            return FetchFile(fileName, id, IsFilePending(id));
        }

        [HttpGet]
        [Route("get-attachments-info")]
        public ActionResult GetAttachmentsInfo(int? id, Guid? tempId)
        {
            var pending = tempId.HasValue ? TicketDeskFileStore.ListAttachmentInfo(tempId.Value.ToString(), true) : new TicketDeskFileInfo[0];
            var attached = id.HasValue ? TicketDeskFileStore.ListAttachmentInfo(id.Value.ToString(CultureInfo.InvariantCulture), false) : new TicketDeskFileInfo[0];

            var files = pending.Select(f => tempId != null ? new
            {
                f.Name,
                f.Size,
                isAttached = false,
                Type = MimeTypeMap.GetMimeType(Path.GetExtension(f.Name)),
                Url = Url.RouteUrl("GetPendingFile", new { Id = tempId.Value, FileName = f.Name, })
            } : null)
            .Union(attached.Select(f => id != null ? new
            {
                f.Name,
                f.Size,
                isAttached = true,
                Type = MimeTypeMap.GetMimeType(Path.GetExtension(f.Name)),
                Url = Url.RouteUrl("GetAttachedFile", new { Id = id.Value, FileName = f.Name })
            } : null));


            return new JsonCamelCaseResult
            {
                Data = files,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        private bool IsFilePending(string containerId)
        {
            Guid tId;
            return Guid.TryParse(containerId, out tId);
        }

        private ActionResult FetchFile(string fileName, string container, bool isPending)
        {
            var fstream = TicketDeskFileStore.GetFile(fileName, container, isPending);
            return new FileStreamResult(fstream, "application/octet-stream");//always send it back as octet-stream so client browser actually downloads it, instead of displaying it on-screen
        }
    }
}

TicketDesk.Web.Client/Controllers/TicketController.cs
// TicketDesk - Attribution notice
// Contributor(s):
//
//      Stephen Redd (https://github.com/stephenredd)
//
// This file is distributed under the terms of the Microsoft Public 
// License (Ms-PL). See http://opensource.org/licenses/MS-PL
// for the complete terms of use. 
//
// For any distribution that contains code from this file, this notice of 
// attribution must remain intact, and a copy of the license must be 
// provided to the recipient.

using System;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using TicketDesk.Domain;
using TicketDesk.Domain.Model;
using TicketDesk.IO;
using TicketDesk.Localization.Controllers;

namespace TicketDesk.Web.Client.Controllers
{
    /// <summary>
    /// Class TicketController.
    /// </summary>
    [RoutePrefix("ticket")]
    [Route("{action=index}")]
    [TdAuthorize(Roles = "TdInternalUsers,TdHelpDeskUsers,TdAdministrators")]
    public class TicketController : Controller
    {
        private TdDomainContext Context { get; set; }
        public TicketController(TdDomainContext context)
        {
            Context = context;
        }

        public RedirectToRouteResult Index()
        {
            return RedirectToAction("Index", "TicketCenter");
        }

        [Route("{id:int}")]
        public async Task<ActionResult> Index(int id)
        {
           
            var model = await Context.Tickets.Include(t => t.TicketSubscribers).FirstOrDefaultAsync(t => t.TicketId == id);
            if (model == null)
            {
                return RedirectToAction("Index", "TicketCenter");
            }
            ViewBag.IsEditorDefaultHtml = Context.TicketDeskSettings.ClientSettings.GetDefaultTextEditorType() == "summernote";

            return View(model);
        }

        [Route("new")]
        public async Task<ActionResult> New()
        {

            var model = new Ticket
            {
                Owner = Context.SecurityProvider.CurrentUserId,
                IsHtml = Context.TicketDeskSettings.ClientSettings.GetDefaultTextEditorType() == "summernote"
            };

            await SetProjectInfoForModelAsync(model);

            ViewBag.TempId = Guid.NewGuid();

            return View(model);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateOnlyIncomingValues]
        [ValidateInput(false)]
        [Route("new")]
        public async Task<ActionResult> New(Ticket ticket, Guid tempId)
        {
            if (ticket.IsHtml)
            {
                ticket.Details = ticket.Details.StripHtmlWhenEmpty();
                if (string.IsNullOrEmpty(ticket.Details))
                {
                    ModelState.AddModelError("Details", Strings.RequiredField);
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (await CreateTicketAsync(ticket, tempId))
                    {
                        return RedirectToAction("Index", new { id = ticket.TicketId });
                    }
                }
                // ReSharper disable once EmptyGeneralCatchClause
                catch (DbEntityValidationException)
                {

                    //TODO: catch rule exceptions? or can annotations handle this fully now?
                }

            }
            ViewBag.TempId = tempId;
            await SetProjectInfoForModelAsync(ticket);
            return View(ticket);
        }

        [Route("ticket-files")]
        public ActionResult TicketFiles(int ticketId)
        {
            //WARNING! This is also used as a child action and cannot be made async in MVC 5
            var attachments = TicketDeskFileStore.ListAttachmentInfo(ticketId.ToString(CultureInfo.InvariantCulture), false);
            ViewBag.TicketId = ticketId;
            return PartialView("_TicketFiles", attachments);
        }

        [Route("ticket-events")]
        public ActionResult TicketEvents(int ticketId)
        {
            //WARNING! This is also used as a child action and cannot be made async in MVC 5
            var ticket = Context.Tickets.Find(ticketId);
            return PartialView("_TicketEvents", ticket.TicketEvents);
        }

        [Route("ticket-details")]
        public ActionResult TicketDetails(int ticketId)
        {
            //WARNING! This is also used as a child action and cannot be made async in MVC 5
            var ticket = Context.Tickets.Find(ticketId);
            ViewBag.DisplayProjects = Context.Projects.Any();

            return PartialView("_TicketDetails", ticket);
        }

        [Route("change-ticket-subscription")]
        [HttpPost]
        public async Task<JsonResult> ChangeTicketSubscription(int ticketId)
        {
            var userId = Context.SecurityProvider.CurrentUserId;
            var ticket = await Context.Tickets.Include(t => t.TicketSubscribers).Include(t => t.TicketEvents.Select(e => e.TicketEventNotifications)).FirstOrDefaultAsync(t => t.TicketId == ticketId);
            var subscriber =
                ticket.TicketSubscribers.FirstOrDefault(s => s.SubscriberId == Context.SecurityProvider.CurrentUserId);
            var isSubscribed = false;
            if (subscriber == null)
            {
                subscriber = new TicketSubscriber
                {
                    SubscriberId = userId,
                };
                ticket.TicketSubscribers.Add(subscriber);
                isSubscribed = true;
            }
            else
            {
                ticket.TicketSubscribers.Remove(subscriber);
            }
            await Context.SaveChangesAsync();
            return new JsonCamelCaseResult { Data = new { IsSubscribed = isSubscribed } };
        }

        private async Task SetProjectInfoForModelAsync(Ticket ticket)
        {
            if (ticket.ProjectId == default(int))
            {
                var projects = await Context.Projects.Select(s=>s.ProjectId).ToListAsync();
                var isMulti = (projects.Count > 1);
                ViewBag.IsMultiProject = isMulti;
               
                //set to first project if only one project exists, otherwise use user's selected project
                ticket.ProjectId = (isMulti) ? await Context.UserSettingsManager.GetUserSelectedProjectIdAsync(Context) : projects.FirstOrDefault(); 
            }
        }


        private async Task<bool> CreateTicketAsync(Ticket ticket, Guid tempId)
        {

            Context.Tickets.Add(ticket);
            await Context.SaveChangesAsync();
            ticket.CommitPendingAttachments(tempId);

            return ticket.TicketId != default(int);
        }

    }
}

TicketDesk.Web.Client/Views/Ticket/Index.cshtml
@*
    TicketDesk - Attribution notice
    Contributor(s):

         Stephen Redd (https://github.com/stephenredd)
         Ashley Medway (https://github.com/AshleyMedway)

    This file is distributed under the terms of the Microsoft Public
    License (Ms-PL). See http://opensource.org/licenses/MS-PL
    for the complete terms of use.

    For any distribution that contains code from this file, this notice of
    attribution must remain intact, and a copy of the license must be
    provided to the recipient.
*@
@using TicketDesk.Localization.Views.Ticket

@using Microsoft.AspNet.Identity
@using TicketDesk.Domain.Model
@model Ticket

@section title
{
    @string.Format(Index.Title, Model.TicketId)
}

@section scripts
{
    @Styles.Render("~/content/editor")
    @Styles.Render("~/content/select2")
    @Styles.Render("~/content/summernote")
    @Styles.Render("~/content/datepicker")
    @Scripts.Render("~/bundles/editor")
    @Scripts.Render("~/bundles/select2")
    @Scripts.Render("~/bundles/select2_locale_" + CultureHelper.GetCurrentCulture())
    @Scripts.Render("~/bundles/markdown")
    @Scripts.Render("~/bundles/editticket")
    @Scripts.Render("~/bundles/summernote")
    @Scripts.Render("~/bundles/summernote_locale_" + CultureHelper.GetCurrentCulture())
    @Scripts.Render("~/bundles/datepicker")


    <script type="text/javascript">

        $(document).ready(function() {
            $.ajaxSetup({ cache: false });
            var tdConfig = {
                loadActivityUrl: '@Url.Action("LoadActivity", "TicketActivity", new {ticketId = Model.TicketId})',
                activityButtonsUrl: '@Url.Action("ActivityButtons", "TicketActivity", new {ticketId = Model.TicketId})',
                eventPanelUrl: '@Url.Action("TicketEvents", "Ticket", new {ticketId = Model.TicketId})',
                loadDetailsUrl: '@Url.Action("TicketDetails", "Ticket", new {ticketId = Model.TicketId})',
                attachmentsPanelUrl: '@Url.Action("TicketFiles", "Ticket", new {ticketId = Model.TicketId})',
                changeTicketSubscription: '@Url.Action("ChangeTicketSubscription", "Ticket", new {ticketId = Model.TicketId})',
                isSubscribed: @(Model.TicketSubscribers.Any(s => s.SubscriberId == User.Identity.GetUserId()) ? "true" : "false"),
                uploaderConfig: {
                    dropzoneUploadUrl: '@Url.Action("Upload", "File")',
                    getAttachmentsUrl: '@Url.Action("GetAttachmentsInfo", "File")',
                    defaultThumbnailUrl: '@Url.Content("~/content/images/general-file.png")',
                    deleteFileUrl: '@Url.Action("Delete", "File")',
                    ticketId: @Model.TicketId
                    },
                tagsConfig: {
                    tagAutoCompleteUrl: '@Url.Action("TagList", "AutoComplete")',
                },
                detailsConfig: {
                    isHtml: @(Model.IsHtml ? "true" : "false")
                    },
                isEditorDefaultHtml: @(ViewBag.IsEditorDefaultHtml? "true" : "false")
                };
            window.editTicket.activate(tdConfig);
        });
    </script>
}

<main role="main">
    <div id="ticketDetailPanel" class="panel panel-info">
        @Html.Action("TicketDetails", new { ticketId = Model.TicketId })
    </div>

    <div class="panel panel-success">
        <div class="panel-heading" style="">
            <div class="btn-toolbar" role="toolbar">
                <div id="activityButtonsPanel">
                    @Html.Action("ActivityButtons", "TicketActivity", new {ticketId = Model.TicketId})
                </div>
            </div>
        </div>
        <section id="activityPanel"></section>
    </div>
    <div id="attachmentsPanel">
        @Html.Action("TicketFiles", new { ticketId = Model.TicketId })
    </div>
    <div class="panel panel-info">
        <div class="panel-heading panel-title" style="padding: 3px 5px;">
            @Index.Activity
        </div>
        <div id="eventPanel" class="panel-body">
            @Html.Action("TicketEvents", new { ticketId = Model.TicketId })
        </div>
    </div>
    <p>
        @Html.ActionLink(Index.BackOption, "Index", "TicketCenter")
    </p>
</main>

TicketDesk.Web.Client/Views/Ticket/_TicketDetails.cshtml
@*
    TicketDesk - Attribution notice
    Contributor(s):

         Stephen Redd (https://github.com/stephenredd)

    This file is distributed under the terms of the Microsoft Public
    License (Ms-PL). See http://opensource.org/licenses/MS-PL
    for the complete terms of use.

    For any distribution that contains code from this file, this notice of
    attribution must remain intact, and a copy of the license must be
    provided to the recipient.
*@
@using TicketDesk.Localization.Views.Ticket
@using TicketDesk.Domain
@using TicketDesk.Domain.Model
@model Ticket

<div class="panel-heading" style="padding: 3px 5px;">
    <div class="row">
        <div class="row-same-height row-full-height">
            <div class="col-xs-2 col-sm-2 col-xs-height col-full-height text-center panel-title" style="border-right: 1px solid #dcdcdc;">
                @Model.TicketStatus.GetDisplayName()
            </div>
            <div class="col-xs-2 col-sm-1 col-xs-height col-full-height text-center panel-title" style="border-right: 1px solid #dcdcdc;">
                #@Model.TicketId
            </div>
            <div class="col-xs-7 col-sm-9 col-xs-height col-full-height panel-title">
                @Model.Title
            </div>
            <div class="col-xs-1 col-xs-height col-full-height">
                <div class="pull-right">
                    <button id="watch" type="button" class="btn btn-default"
                            data-toggle="tooltip"
                            data-placement="bottom"
                            title="">
                        <i class="fa fa-eye"></i> <span class="hidden-sm hidden-xs"></span>
                    </button>
                </div>
            </div>

        </div>
    </div>

</div>
<div class="panel-body" style="padding: 0">
    <div class="row row-no-padding row-same-height row-full-height" style="width: 100%;margin:0">
        <div class="col-md-8 col-sm-8 col-xs-12 col-xs-height col-full-height">
            <div class="container-fluid" style="padding: 0;">
                <div class="col-xs-12" style="border-bottom: 1px solid #B3CBDF; padding: 5px; background-color: #F7F7F7;">
                    <div class="pull-right">
                        @if (ViewBag.DisplayProjects ?? false)
                        {
                            <div class="text-primary">
                                <i class="fa fa-book"></i>
                                @Model.Project.ProjectName
                            </div>
                        }
                        @if (!string.IsNullOrEmpty(Model.TagList))
                        {
                            <div class="text-muted text-default">

                                @foreach (var tag in Model.TagList.Split(','))
                                {
                                    <div><i class="fa fa-tag"></i> @tag</div>
                                }
                            </div>
                        }


                    </div>
                    <div>
                        <div>@(string.IsNullOrEmpty(Model.Priority) ? string.Empty : string.Format(Index.Priority, Model.Priority)) @Model.Category @Model.TicketType</div>

                        <div>
                            @Html.Raw(string.Format(Index.AssignedTo, string.IsNullOrEmpty(Model.AssignedTo) ? "<span class='label label-warning'>" + Index.Unassigned + "</span>" : Model.GetAssignedToInfo().DisplayName))
                        </div>
                        <div>
                            @Html.Raw(string.Format(Index.OwnedBy, Model.GetOwnerInfo().DisplayName))
                        </div>
                        <div class="hidden-sm hidden-md hidden-lg">
                            @Html.Raw(string.Format(Index.UpdatedBy, Model.GetLastUpdatedByInfo().DisplayName, Model.LastUpdateDate.DateTime.ToShortDateString(), Model.LastUpdateDate.DateTime.ToShortTimeString()))
                        </div>
                    </div>
                </div>
            </div>
            <div class="" style="margin: 0; padding: 0;">
                <div class="" id="detailsText" style="height: 200px; overflow: auto; margin: 0; padding: 5px;">
                    @Model.HtmlDetails()
                </div>
                <div id="detailTextExpander" class="expanderButton" style="height: 20px; display: none;">
                    <i id="expandersymbol" class="fa fa-chevron-down text-center"></i>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 hidden-xs col-sm-height col-full-height col-top" style="border-left: 1px solid #B3CBDF;background-color: #F7F7F7;">
            <div class="container-fluid" style="padding: 0;">
                <aside class="small">
                    <div style="padding: 5px;">
                        <div class="row">
                            @Html.LabelFor(m => m.TicketStatus, new {@class = "col-sm-5 col-lg-4 text-right"})
                            <div class="col-sm-7 col-lg-8">
                                @Model.TicketStatus.GetDisplayName()
                            </div>
                        </div>
                        <div class="row">
                            @Html.LabelFor(m => m.DueDate, new { @class = "col-sm-5 col-lg-4 text-right" })
                            <div class="col-sm-7 col-lg-8">
                                @if (Model.DueDate.HasValue)
                                {
                                    @Model.DueDateAsString
                                }
                            </div>
                        </div>
                        <div class="row">
                            @Html.LabelFor(m => m.TargetDate, new { @class = "col-sm-5 col-lg-4 text-right" })
                            <div class="col-sm-7 col-lg-8">
                                @if (Model.TargetDate.HasValue)
                                {
                                    @Model.TargetDateAsString
                                }
                            </div>
                        </div>
                        <div class="row">
                            @Html.LabelFor(m => m.ResolutionDate, new { @class = "col-sm-5 col-lg-4 text-right" })
                            <div class="col-sm-7 col-lg-8">
                                @if (Model.ResolutionDate.HasValue)
                                {
                                    @Model.ResolutionDateAsString
                                }
                            </div>
                        </div>
                        <div class="row">
                            @Html.LabelFor(m => m.LastUpdateBy, new {@class = "col-sm-5 col-lg-4 text-right"})
                            <div class="col-sm-7 col-lg-8">
                                @Model.GetLastUpdatedByInfo().DisplayName
                            </div>
                        </div>
                        <div class="row">
                            @Html.LabelFor(m => m.LastUpdateDate, new {@class = "col-sm-5 col-lg-4 text-right"})
                            <div class="col-sm-7 col-lg-8">
                                @Model.LastUpdateDate.DateTime.ToShortDateString() @Model.LastUpdateDate.DateTime.ToShortTimeString()
                            </div>
                        </div>

                        <div class="row">
                            @Html.LabelFor(m => m.CurrentStatusSetBy, new {@class = "col-sm-5 col-lg-4 text-right"})
                            <div class="col-sm-7 col-lg-8">
                                @Model.GetCurrentStatusSetByInfo().DisplayName
                            </div>
                        </div>
                        <div class="row">
                            @Html.LabelFor(m => m.CurrentStatusDate, new {@class = "col-sm-5 col-lg-4 text-right"})
                            <div class="col-sm-7 col-lg-8">
                                @Model.CurrentStatusDate.DateTime.ToShortDateString() @Model.CurrentStatusDate.DateTime.ToShortTimeString()
                            </div>
                        </div>
                        <div class="row">
                            @Html.LabelFor(m => m.CreatedBy, new {@class = "col-sm-5 col-lg-4 text-right"})
                            <div class="col-sm-7 col-lg-8">
                                @Model.GetCreatedByInfo().DisplayName
                            </div>
                        </div>
                        <div class="row">
                            @Html.LabelFor(m => m.CreatedDate, new {@class = "col-sm-5 col-lg-4 text-right"})
                            <div class="col-sm-7 col-lg-8">
                                @Model.CreatedDate.DateTime.ToShortDateString() @Model.CreatedDate.DateTime.ToShortTimeString()
                            </div>
                        </div>
                        <div class="row">
                            @Html.LabelFor(m => m.EstimatedDuration, new { @class = "col-sm-5 col-lg-4 text-right" })
                            <div class="col-sm-7 col-lg-8">
                                @Model.EstimatedDuration
                            </div>
                        </div>
                        <div class="row">
                            @Html.LabelFor(m => m.ActualDuration, new { @class = "col-sm-5 col-lg-4 text-right" })
                            <div class="col-sm-7 col-lg-8">
                                @Model.ActualDuration
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-sm-5 col-lg-4 text-right">@Index.Subscribers</label>
                            <div class="col-sm-7 col-lg-8">

                                @foreach (var sub in Model.TicketSubscribers)
                                {
                                <div>@sub.GetSubscriberDisplayInfo().DisplayName</div>
                                }
                            </div>
                        </div>
                    </div>

                </aside>
            </div>
        </div>
    </div>
</div>

TicketDesk.Web.Client/Views/Ticket/_TicketEvents.cshtml
@*
    TicketDesk - Attribution notice
    Contributor(s):

         Stephen Redd (https://github.com/stephenredd)

    This file is distributed under the terms of the Microsoft Public
    License (Ms-PL). See http://opensource.org/licenses/MS-PL
    for the complete terms of use.

    For any distribution that contains code from this file, this notice of
    attribution must remain intact, and a copy of the license must be
    provided to the recipient.
*@

@using Microsoft.AspNet.Identity
@using TicketDesk.Domain.Model
@model IEnumerable<TicketEvent>

@foreach (var evt in Model.OrderByDescending(c => c.EventDate))
{
    var userId = User.Identity.GetUserId();
    
    var pnlType = (evt.EventBy == userId)? "panel-success": "panel-default";
    <div class="panel panel-default">
        <div class="panel-heading"  style="padding: 5px;">
            <div><strong>@evt.GetEventByInfo().DisplayName</strong> @evt.EventDescription</div>

            <div class="text-muted small" style="text-indent: 1em;">
                @evt.EventDate.ToString("D")
                @evt.EventDate.ToString("t")
            </div>
        </div>
        @{
            var cmt = evt.HtmlComment();
            if (!string.IsNullOrEmpty(cmt.ToString()))
            {
                <div class="panel-body" style="padding: 5px;">@cmt</div>
            }
        }
    </div>
}

TicketDesk.Web.Client/Views/Ticket/_TicketFiles.cshtml
@*
    TicketDesk - Attribution notice
    Contributor(s):

         Stephen Redd (https://github.com/stephenredd)

    This file is distributed under the terms of the Microsoft Public
    License (Ms-PL). See http://opensource.org/licenses/MS-PL
    for the complete terms of use.

    For any distribution that contains code from this file, this notice of
    attribution must remain intact, and a copy of the license must be
    provided to the recipient.
*@
@using TicketDesk.Localization.Views.Ticket

@using TicketDesk.IO
@model IEnumerable<TicketDeskFileInfo>
@{

    if (Model != null && Model.Any())
    {
        <div class="panel panel-info" style="padding-top: 0; padding-bottom: 0;">
            <div class="panel-heading panel-title" style="padding: 3px 5px;">
                @Index.Files
            </div>
            <div class="panel-body" style="">
                <ul class="list-unstyled list-inline">
                    @foreach (var file in Model)
                    {
                        <li>
                            <a href="@Url.RouteUrl("GetAttachedFile", new {Id = ViewBag.TicketId, FileName = file.Name})"><i class="fa fa-file fa-align-left"></i> @file.Name</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    }
}