TicketDesk.Web.Client/Controllers/UserAdministrationController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Hosting;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PagedList;
using TicketDesk.Domain;
using TicketDesk.Localization.Controllers;
using TicketDesk.PushNotifications;
using TicketDesk.PushNotifications.Model;
using TicketDesk.Web.Client.Models;
using TicketDesk.Web.Identity;
using TicketDesk.Web.Identity.Model;

namespace TicketDesk.Web.Client.Controllers
{
    [RoutePrefix("admin")]
    [Route("{action=index}")]
    [TdAuthorize(Roles = "TdAdministrators")]
    public class UserAdministrationController : Controller
    {
        private TicketDeskUserManager UserManager { get; set; }
        private TicketDeskRoleManager RoleManager { get; set; }
        private TdDomainContext DomainContext { get; set; }

        public UserAdministrationController(
            TicketDeskUserManager userManager, 
            TicketDeskRoleManager roleManager,
            TdDomainContext domainContext)
        {
            UserManager = userManager;
            RoleManager = roleManager;
            DomainContext = domainContext;
        }

        [Route("users/{page:int?}")]
        public async Task<ActionResult> Index(int? page)
        {
            ViewBag.AllRolesList = await RoleManager.Roles.ToListAsync();
            var users = await GetUsersForListAsync(page ?? 1);
            return View(users);
        }

        [Route("users/page/{page:int?}")]
        public async Task<ActionResult> PageList(int? page = 1)
        {
            ViewBag.AllRolesList = await RoleManager.Roles.ToListAsync();
            var users = await GetUsersForListAsync(page ?? 1);
            return PartialView("_UserList",users);

        }

        [Route("user/delete/{id?}")]
        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            //does user to delete exist?
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return RedirectToAction("Index");
            }

            //checks for current user
            var currentUser = await UserManager.FindByIdAsync(this.User.Identity.GetUserId());
            if (user == currentUser)
            {
                ModelState.AddModelError("", Strings.CannotRemoveCurrentUser);
            }
            else
            {
                try
                {
                    UserManager.Delete(user);
                    return RedirectToAction("Index");
                }
                catch { }
                ModelState.AddModelError("", Strings.UnableToRemoveUser);
            }

            return RedirectToAction("Edit", new { id });
        }

        [Route("user/{id?}")]
        public async Task<ActionResult> Edit(string id)
        {
            //ViewBag.AllRolesList = await RoleManager.Roles.ToListAsync();
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return RedirectToAction("Index");
            }
            var model = new UserAccountInfoViewModel(user, user.Roles.Select(r => r.RoleId));
            var tdPendingRole = RoleManager.Roles.FirstOrDefault(r => r.Name == "TdPendingUsers");
            
            ViewBag.TdPendingUsersRoleId = tdPendingRole == null ? "" : tdPendingRole.Id; 
            return View(model);
        }

        [Route("user/{id?}")]
        [HttpPost]
        public async Task<ActionResult> Edit(UserAccountInfoViewModel model)
        {
            var tdPendingRole = RoleManager.Roles.FirstOrDefault(r => r.Name == "TdPendingUsers");
            ViewBag.TdPendingUsersRoleId = tdPendingRole == null ? "" : tdPendingRole.Id;
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await UserManager.FindByIdAsync(model.User.Id);
            var demoMode = (ConfigurationManager.AppSettings["ticketdesk:DemoModeEnabled"] ?? "false").Equals("true", StringComparison.InvariantCultureIgnoreCase);
            if (demoMode && model.User.Email.EndsWith("@example.com", StringComparison.InvariantCultureIgnoreCase))
            {
                ModelState.AddModelError("Profile", Strings.UnableToChangeDemoUser);
            }
            else
            {
                //deal with locks first
                if (await SetLockout(model, user))
                {
                    //do user info updates
                    if (await UpdateUserInfo(user, model))
                    {

                        //if any roles other than pending are selected, make sure we remove the pending role from the model first
                        if (tdPendingRole != null)
                        {
                            if (model.Roles.Any(r => r != tdPendingRole.Id))
                            {
                                var mRoles = model.Roles.ToList();
                                mRoles.Remove(tdPendingRole.Id);
                                model.Roles = mRoles;
                            }
                        }

                        //get role changes
                        var roleIdsToRemove = user.Roles.Select(ur => ur.RoleId).Except(model.Roles).ToList();

                        if (User.Identity.GetUserId() == user.Id)
                        {
                            //stop current user from removing their own admin role
                            roleIdsToRemove = roleIdsToRemove.Except(RoleManager.Roles.Where(r => r.Name == "tdAdministrators").Select(r => r.Id)).ToList();
                        }


                        var roleIdsToAdd = model.Roles.Except(user.Roles.Select(ur => ur.RoleId)).ToList();
                        //do role removes
                        if (await RemoveRoles(roleIdsToRemove, user))
                        {
                            //do role adds
                            if (await AddRoles(roleIdsToAdd, user))
                            {
                                //everything worked, return to index (if anything failed, will return to the edit user view)
                                return RedirectToAction("Index");
                            }
                        }
                    }
                }               
            }
            //Since the above operations could be partially committed before a failure, 
            //  we will re-get the user so we are sure the screen will accurately show 
            //  the current data. Model errors will have been added by the respective 
            //  update operations that failed
            user = await UserManager.FindByIdAsync(model.User.Id);
            model = new UserAccountInfoViewModel(user, user.Roles.Select(r => r.RoleId));
            return View(model);
        }

        [Route("new")]
        public ActionResult New()
        {
            return View();
        }

        [Route("new")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> New(UserRegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new TicketDeskUser { UserName = model.UserName, Email = model.Email, DisplayName = model.DisplayName };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await UserManager.AddToRolesAsync(user.Id, DomainContext.TicketDeskSettings.SecuritySettings.DefaultNewUserRoles.ToArray());
                    HostingEnvironment.QueueBackgroundWorkItem(ct =>
                    {
                        using (var notificationContext = new TdPushNotificationContext())
                        {
                            notificationContext.SubscriberPushNotificationSettingsManager.AddSettingsForSubscriber(
                                new SubscriberNotificationSetting
                                {
                                    SubscriberId = user.Id,
                                    IsEnabled = true,
                                    PushNotificationDestinations = new[]
                                    {
                                        new PushNotificationDestination()
                                        {
                                            DestinationType = "email",
                                            DestinationAddress = user.Email,
                                            SubscriberName = user.DisplayName
                                        }
                                    }
                                });
                            notificationContext.SaveChanges();
                        }
                    });

                    return RedirectToAction("Index");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        private async Task<IPagedList<UserAccountInfoViewModel>> GetUsersForListAsync(int page)
        {
            var users = await UserManager.Users
                .OrderBy(u => u.DisplayName)
                .Select(u => new UserAccountInfoViewModel
                {
                    User = u,
                    Roles = u.Roles.Select(r => r.RoleId),
                    IsLocked = (u.LockoutEndDateUtc ?? DateTime.MinValue) > DateTime.UtcNow &&
                               (u.LockoutEndDateUtc ?? DateTime.MinValue) < DateTime.MaxValue,
                    IsDisabled = (u.LockoutEndDateUtc ?? DateTime.MinValue) == DateTime.MaxValue
                })
                .ToPagedListAsync(page, 25);
            return users;
        }

        private async Task<bool> UpdateUserInfo(TicketDeskUser user, UserAccountInfoViewModel model)
        {

TicketDesk.Web.Client/Views/UserAdministration/Edit.cshtml
@using TicketDesk.Localization.Views.UserAdministration
@model TicketDesk.Web.Client.Models.UserAccountInfoViewModel

@section title
{
    @Edit.Title
}
@section scripts
{
    @Styles.Render("~/content/select2")
    @Scripts.Render("~/bundles/select2")
    @Scripts.Render("~/bundles/select2_locale_" + CultureHelper.GetCurrentCulture())
    @Scripts.Render("~/bundles/admin-edit-user")
    <script type="text/javascript">
        $(document).ready(function () {
            window.adminEditUser.activate({ pendingOptionId: '@ViewBag.TdPendingUsersRoleId' });
        });
    </script>
}
<main>
    <div class="container">
        <fieldset>
            <legend class="col-lg-8 col-lg-offset-2 col-md-9 col-md-offset-1 col-sm-12">@Edit.Legend</legend>
            <div class="col-lg-7 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-12">
                @using (Html.BeginForm("Edit", "UserAdministration", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(m => m.User.Id);
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h2 class="panel-title">@Edit.Header</h2>
                        </div>
                        <div class="panel-body">
                            @Html.ValidationSummary("", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(m => m.User.UserName, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(m => m.User.UserName, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.User.Email, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(m => m.User.Email, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.User.DisplayName, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(m => m.User.DisplayName, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.IsLocked, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-9">
                                    <label class="checkbox-inline">
                                        @Html.EditorFor(model => model.IsLocked)
                                        @Html.PromptFor(model => model.IsLocked)
                                        @if (Model.IsLocked)
                                        {
                                            <span class="text-muted small">
                                                (unlock at: @Model.User.LockoutEndDateUtc.Value.ToLocalTime().ToString())
                                            </span>
                                        }
                                    </label>
                                    @Html.ValidationMessageFor(model => model.IsLocked, "", new { @class = "text-danger" })
                                    @Html.DescriptionFor(model => model.IsLocked, "help-block", "span")
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.IsDisabled, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-9">
                                    <label class="checkbox-inline">
                                        @Html.EditorFor(model => model.IsDisabled)
                                        @Html.PromptFor(model => model.IsDisabled)
                                    </label>
                                    @Html.ValidationMessageFor(model => model.IsDisabled, "", new { @class = "text-danger" })
                                    @Html.DescriptionFor(model => model.IsDisabled, "help-block", "span")
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Roles, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-9">
                                    <div class="input-group input-group-sm">
                                        @Html.ListBoxFor(model => model.Roles, Model.UserRolesList, new { id = "userroles", @class = "form-control input-sm" })
                                        @Html.ValidationMessageFor(model => model.Roles, "", new { @class = "text-danger" })
                                        @Html.DescriptionFor(model => model.Roles, "help-block", "span")
                                        <span class="input-group-btn"
                                              data-toggle="tooltip"
                                              data-placement="top"
                                              title="@Edit.ShowRoleDescriptions">
                                            <button class="btn btn-default btn-sm" type="button" data-toggle="collapse" href="#collapseRoleDescription" aria-expanded="false" aria-controls="collapseRoleDescription">
                                                <i class="fa fa-info"></i>
                                            </button>
                                        </span>
                                    </div>
                                    <div class="collapse" id="collapseRoleDescription">
                                        <div class="well" style="margin-top: 5px;">
                                            <dl class="list list-inline">
                                                <dt>
                                                    @Edit.PendingApproval
                                                </dt>
                                                <dd class="text-muted">
                                                    @Edit.PendingApproval_Description
                                                </dd>
                                                <dt>
                                                    @Edit.InternalUsers
                                                </dt>
                                                <dd class="text-muted">
                                                    @Edit.InternalUsers_Description
                                                </dd>
                                                <dt>
                                                    @Edit.HelpDeskStaff
                                                </dt>
                                                <dd class="text-muted">
                                                    @Edit.HelpDeskStaff_Description
                                                </dd>
                                                <dt>
                                                    @Edit.Administrators
                                                </dt>
                                                <dd class="text-muted">
                                                    @Edit.Administrators_Description
                                                </dd>
                                            </dl>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <div class="pull-right">
                                <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#delete-confirm">
                                    <i class="fa fa-remove"></i>&nbsp;&nbsp;@Edit.DeleteOption
                                </a>
                            </div>
                            <div class="">
                                <button type="submit" class="btn btn-success" tabindex="10"><i class="fa fa-save"></i>&nbsp;&nbsp;@Edit.SaveOption</button>&nbsp;&nbsp;
                                @Html.ActionLink(Edit.BackOption, "Index")
                            </div>
                        </div>
                    </div>
                }
            </div>
        </fieldset>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="delete-confirm" tabindex="-1" role="dialog" aria-labelledby="delete-confirm-label" aria-hidden="true">
        <div class="modal-dialog">
            @using (Html.BeginForm("Delete", "UserAdministration", new { Model.User.Id }, FormMethod.Post, new { @class = "form", role = "form" }))
            {
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="@Edit.CloseOption"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="delete-confirm-label">@Edit.DeleteConfirmation</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <div class="alert alert-danger">
                                @Edit.DeleteAlert
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">@Edit.CancelOption</button>
                        <button type="submit" class="btn btn-primary">@Edit.DeleteOption</button>
                    </div>
                </div>
            }
        </div>
    </div>
</main>

TicketDesk.Web.Client/Views/UserAdministration/Index.cshtml
@using TicketDesk.Localization.Views.UserAdministration
@model PagedList.IPagedList<TicketDesk.Web.Client.Models.UserAccountInfoViewModel>
@section title{
    @Index.Title
}
@section scripts
{
    @Scripts.Render("~/bundles/admin-users")
    <script type="text/javascript">
        $(document).ready(function () {
            window.adminUsers.activate();
        });
    </script>
}
<main>
    <div class="container">
        <fieldset>
            <legend class="col-sm-12">@Index.Legend</legend>
            <div class="col-sm-12">
                @Html.Partial("_UserList", Model)
            </div>
            <div class="panel-footer">
                <div class="">
                    <a href="@Url.Action("New", "UserAdministration")" class="btn btn-primary">
                        <i class="fa fa-plus"></i>&nbsp;&nbsp;@Index.NewUser
                    </a>
                </div>
            </div>
        </fieldset>
    </div>
</main>

TicketDesk.Web.Client/Views/UserAdministration/New.cshtml
@using TicketDesk.Localization.Views.UserAdministration
@model TicketDesk.Web.Client.Models.UserRegisterViewModel
@section title
{
    @New.Title
}
@section Scripts {
}
<main>
    <div class="container">
        <fieldset>
            <legend class="col-lg-8 col-lg-offset-2 col-md-9 col-md-offset-1 col-sm-12">@New.Legend</legend>
            <div class="col-lg-7 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-12">
                @using (Html.BeginForm("New", "UserAdministration", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h2 class="panel-title">@New.Header</h2>
                        </div>
                        <div class="panel-body">
                            @Html.ValidationSummary("", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(m => m.UserName, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Email, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Password, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-9">
                                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-9">
                                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.DisplayName, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(m => m.DisplayName, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <button type="submit" class="btn btn-success" tabindex="10">@New.SaveOption</button>&nbsp;&nbsp;
                        </div>
                    </div>
                }
            </div>
        </fieldset>
    </div>
</main>

TicketDesk.Web.Client/Views/UserAdministration/_UserList.cshtml
@using TicketDesk.Localization.Views.UserAdministration
@using PagedList.Mvc
@model PagedList.IPagedList<TicketDesk.Web.Client.Models.UserAccountInfoViewModel>
@{
    var ajaxPagerOptions = new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "userListBody", OnBegin = "adminUsers.paging.beginChangePage", OnSuccess = "adminUsers.completeChangeList", OnFailure = "adminUsers.completeChangeList" };
}
<div id="userListBody">
    <div class="panel panel-default">
        <div class="panel-body" style="padding: 0;">
            <div class="table-responsive">
                <table class="table table-striped table-condensed table-hover ">
                    <tr>
                        <th>
                            @Index.User
                        </th>
                        <th>
                            @Index.Roles
                        </th>
                        <th>
                            @Index.Status
                        </th>
                    </tr>
                    @foreach (var account in Model)
                    {
                        <tr class="clickable">
                            <td>
                                <a href="@Url.Action("Edit", "UserAdministration", new {id = account.User.Id})">
                                    @account.User.DisplayName (@account.User.UserName)
                                </a>
                            </td>
                            <td>
                                <ul class="list-unstyled">
                                    @foreach (var role in account.GetRoleNames(ViewBag.AllRolesList))
                                    {
                                        <li class="label label-default">@role</li>
                                    }
                                </ul>
                            </td>
                            <td>
                                <i class="fa fa-2x @(account.IsLocked ? "fa-lock text-danger" : "fa-unlock")"></i>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
        <div class="panel-footer">
            @Html.PagedListPager(Model, page => Url.Action("PageList", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(ajaxPagerOptions))
        </div>
    </div>
</div>