TicketDesk.Web.Client/Controllers/ApplicationSettingsController.cs
// TicketDesk - Attribution notice
// Contributor(s):
//
//      Stephen Redd (https://github.com/stephenredd)
//
// This file is distributed under the terms of the Microsoft Public 
// License (Ms-PL). See http://opensource.org/licenses/MS-PL
// for the complete terms of use. 
//
// For any distribution that contains code from this file, this notice of 
// attribution must remain intact, and a copy of the license must be 
// provided to the recipient.

using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TicketDesk.Domain;
using TicketDesk.Domain.Model;
using TicketDesk.Search.Azure;
using TicketDesk.Search.Common;

namespace TicketDesk.Web.Client.Controllers
{
    [RoutePrefix("admin/application-settings")]
    [Route("{action=index}")]
    [TdAuthorizeAttribute(Roles = "TdAdministrators")]
    public class ApplicationSettingsController : Controller
    {
        private TdDomainContext Context { get; set; }
        private bool IsAzureSearchDetected { get; set; }
        public ApplicationSettingsController(TdDomainContext context)
        {
            Context = context;
            IsAzureSearchDetected = TdSearchContext.Current.IndexManager.GetType() == typeof(AzureIndexProvider);
        }

        public ActionResult Index()
        {
            var dbSetting = Context.TicketDeskSettings;
            ViewBag.IsAzureSearchEnabled = IsAzureSearchDetected;
            return View(dbSetting);
        }

        [HttpPost]
        public ActionResult Index(
            ApplicationSetting settings,
            [ModelBinder(typeof(CommaSeparatedModelBinder))] string[] categories,
            [ModelBinder(typeof(CommaSeparatedModelBinder))] string[] tickettypes,
            [ModelBinder(typeof(CommaSeparatedModelBinder))] string[] priorities,
            List<string> defaultroles,
            string defaultTextEditorType
            )
        {
            var dbSetting = Context.TicketDeskSettings;
            if (ModelState.IsValid && TryUpdateModel(dbSetting))
            {
                dbSetting.SelectLists.CategoryList = categories.ToList();
                dbSetting.SelectLists.PriorityList = priorities.ToList();
                dbSetting.SelectLists.TicketTypesList = tickettypes.ToList();
                dbSetting.SecuritySettings.DefaultNewUserRoles = defaultroles;
                dbSetting.ClientSettings.Settings["DefaultTextEditorType"] = defaultTextEditorType;
                Context.SaveChanges();
            }
            ViewBag.IsAzureSearchEnabled = IsAzureSearchDetected;
            return View(dbSetting);
        }
    }
}

TicketDesk.Web.Client/Views/ApplicationSettings/Index.cshtml
@using TicketDesk.Localization.Views.ApplicationSettings
@using TicketDesk.Domain.Model
@model TicketDesk.Domain.Model.ApplicationSetting

@section title
{
    @Index.Title
}

@section scripts
{
    @Styles.Render("~/content/select2")
    @Scripts.Render("~/bundles/select2")
    @Scripts.Render("~/bundles/select2_locale_" + CultureHelper.GetCurrentCulture())
    @Scripts.Render("~/bundles/application-settings")

    <script type="text/javascript">

        (function () {
            window.applicationSettings.activate(null);
        })();
    </script>
}

<main>
    <div class="container">
        <fieldset>
            <!-- Form Name -->
            <legend class="col-lg-9 col-lg-offset-1 col-sm-12">
                @Index.Legend
            </legend>

            @using (Html.BeginForm("Index", "ApplicationSettings", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="col-lg-9 col-lg-offset-1  col-sm-12">
                    @Html.AntiForgeryToken()

                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h2 class="panel-title">@Index.Global_Header</h2>
                        </div>
                        <div class="panel-body ">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            @Html.HiddenFor(model => model.ApplicationName)

                            <div class="form-group">
                                <label class="col-md-4 col-sm-4 control-label">@Index.Global_Priority</label>
                                <div class="col-md-8 col-sm-8">
                                    <label class="checkbox-inline">
                                        @Html.CheckBoxFor(model => model.Permissions.AllowInternalUsersToEditPriority, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.DisplayNameFor(model => model.Permissions.AllowInternalUsersToEditPriority)
                                    </label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 col-sm-4 control-label">@Index.Global_Tags</label>
                                <div class="col-md-8 col-sm-8">
                                    <label class="checkbox-inline">
                                        @Html.CheckBoxFor(model => model.Permissions.AllowInternalUsersToEditTags, new {htmlAttributes = new {@class = "form-control"}})
                                        @Html.DisplayNameFor(model => model.Permissions.AllowInternalUsersToEditTags)
                                    </label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 col-sm-4 control-label">Owner</label>
                                <div class="col-md-8 col-sm-8">
                                    <label class="checkbox-inline">
                                        @Html.CheckBoxFor(model => model.Permissions.AllowInternalUsersToSetOwner, new {htmlAttributes = new {@class = "form-control"}})
                                        @Html.DisplayNameFor(model => model.Permissions.AllowInternalUsersToSetOwner)
                                    </label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 col-sm-4 control-label">Assigned To</label>
                                <div class="col-md-8 col-sm-8">
                                    <label class="checkbox-inline">
                                        @Html.CheckBoxFor(model => model.Permissions.AllowInternalUsersToSetAssigned, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.DisplayNameFor(model => model.Permissions.AllowInternalUsersToSetAssigned)
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="panel-heading">
                            <h2 class="panel-title">@Index.Settings_Header</h2>
                        </div>
                        <div class="panel-body ">
                            <div class="form-group">
                                <label class="col-md-4 col-sm-4 control-label">@Index.Settings_Editor</label>
                                <div class="col-md-8 col-sm-8">
                                    <div class="radio">
                                        <label class="checkbox-inline">
                                            @Html.RadioButton("DefaultTextEditorType", "summernote", (Model.ClientSettings.GetDefaultTextEditorType() == "summernote"), new { id = "IsSummernote" })
                                            @Index.Settings_Editor_HTML
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label class="checkbox-inline">
                                            @Html.RadioButton("DefaultTextEditorType", "pagedown", (Model.ClientSettings.GetDefaultTextEditorType() == "pagedown"), new { id = "IsPagedown" })
                                            @Index.Settings_Editor_Markdown
                                        </label>
                                    </div>
                                    <div class="help-block">
                                        @Html.Raw(Index.Settings_Editor_Help)
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-heading">
                            <h2 class="panel-title">@Index.List_Header</h2>
                        </div>
                        <div class="panel-body ">
                            <div class="form-group">
                                @Html.LabelFor(model => model.SelectLists.TicketTypesList, new { @class = "col-md-4 col-sm-4 control-label" })
                                <div class="col-md-8 col-sm-8">
                                    <input id="tickettypes" name="tickettypes" class="form-control input-sm" value="@Model.GetTicketTypes()" />
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.SelectLists.CategoryList, new { @class = "col-md-4 col-sm-4 control-label" })
                                <div class="col-md-8 col-sm-8">
                                    <input id="categories" name="categories" class="form-control input-sm" value="@Model.GetCategories()" />
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.SelectLists.PriorityList, new { @class = "col-md-4 col-sm-4 control-label" })
                                <div class="col-md-8 col-sm-8">
                                    <input id="priorities" name="priorities" class="form-control input-sm" value="@Model.GetPriorities()" />
                                </div>
                            </div>
                        </div>
                        <div class="panel-heading">
                            <h2 class="panel-title">@Index.Security_Header</h2>
                        </div>
                        <div class="panel-body ">
                            <div class="form-group">
                                @Html.LabelFor(model => model.SecuritySettings.DefaultNewUserRoles, new { @class = "col-md-4 col-sm-4 control-label" })
                                <div class="col-md-8 col-sm-8">
                                    @Html.ListBox("defaultroles", Model.GetDefaultNewUserRolesList(), new { id = "defaultroles", @class = "form-control input-sm" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.SecuritySettings.DefaultLogonDomain, new { @class = "col-md-4 col-sm-4 control-label" })
                                <div class="col-md-8 col-sm-8">
                                    @Html.EditorFor(model => model.SecuritySettings.DefaultLogonDomain, new { htmlAttributes = new { @class = "form-control input-sm" } })
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <div class="">
                                <button type="submit" class="btn btn-success" tabindex="10"><i class="fa fa-save"></i>&nbsp;&nbsp;@Index.SaveOption</button>&nbsp;&nbsp;

                            </div>
                        </div>

                    </div>
                </div>
            }
        </fieldset>
    </div>
</main>