TicketDesk.Web.Client/Controllers/FirstRunSetupController.cs
// TicketDesk - Attribution notice
// Contributor(s):
//
//      Stephen Redd (https://github.com/stephenredd)
//
// This file is distributed under the terms of the Microsoft Public 
// License (Ms-PL). See http://opensource.org/licenses/MS-PL
// for the complete terms of use. 
//
// For any distribution that contains code from this file, this notice of 
// attribution must remain intact, and a copy of the license must be 
// provided to the recipient.

using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using TicketDesk.Domain;
using TicketDesk.Domain.Legacy;
using TicketDesk.Domain.Migrations;
using TicketDesk.Domain.Model;
using TicketDesk.PushNotifications;
using TicketDesk.PushNotifications.Model;
using TicketDesk.Search.Common;
using TicketDesk.Web.Client.Models;
using TicketDesk.Web.Identity;
using TicketDesk.Web.Identity.Model;

namespace TicketDesk.Web.Client.Controllers
{


    [RoutePrefix("first-run-setup")]
    [Route("{action=index}")]
    [WhenSetupEnabled]
    public class FirstRunSetupController : Controller
    {
        private TicketDeskUserManager UserManager { get; set; }
        private TicketDeskSignInManager SignInManager { get; set; }

        private SystemInfoViewModel Model { get; set; }
        public FirstRunSetupController(
            TicketDeskUserManager userManager,
            TicketDeskSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
            Model = new SystemInfoViewModel();
        }

        // GET: FirstRunSetup
        [Route("", Name = "first-run-setup")]
        [Route("index")]
        public ActionResult Index()
        {

            return View();
        }

        [Route("legacy-migration")]
        public ActionResult LegacyMigration()
        {
            var identityCtx = DependencyResolver.Current.GetService<TdIdentityContext>();
            var userManager = DependencyResolver.Current.GetService<TicketDeskUserManager>();
            var roleManager = DependencyResolver.Current.GetService<TicketDeskRoleManager>();
            if (LegacySecurityMigrator.MigrateSecurity(identityCtx, userManager, roleManager))
            {
                LegacySecurityMigrator.RemoveLegacyMembershipObjects(identityCtx);
            }
            return RedirectToAction("Index");
        }

        [Route("upgrade-database")]
        public async Task<ActionResult> UpgradeDatabase()
        {


            LegacyBackgroundMigrator.BeginMigration(new LegacyMigrator());

            await Task.FromResult(true);




            return RedirectToAction("CheckUpgradeProgress");
        }




        [Route("check-upgrade-progress")]
        public ActionResult CheckUpgradeProgress()
        {

            if (LegacyBackgroundMigrator.MigrationTask != null)
            {
                ViewBag.Refresh = "True";
                ViewBag.Messages = LegacyBackgroundMigrator.MessageStack.ToString()
                    .Replace(System.Environment.NewLine, "<br />");
                var upgradeSuccess = false;
                switch (LegacyBackgroundMigrator.MigrationTask.Status)
                {
                    case TaskStatus.Running:
                    case TaskStatus.WaitingForChildrenToComplete:
                    case TaskStatus.WaitingToRun:
                    case TaskStatus.WaitingForActivation:
                        ViewBag.Status = "Running";
                        ViewBag.Alert = "alert-info";
                        break;
                    case TaskStatus.Canceled:
                        ViewBag.Status = "Canceled";
                        ViewBag.Alert = "alert-error";
                        ViewBag.Refresh = "False";
                        LegacyBackgroundMigrator.Reset();
                        break;
                    case TaskStatus.Faulted:
                        ViewBag.Status = "Failed";
                        ViewBag.Alert = "alert-error";
                        ViewBag.Refresh = "False";
                        LegacyBackgroundMigrator.Reset();
                        break;
                    case TaskStatus.RanToCompletion:
                        ViewBag.Status = "Completed";
                        ViewBag.Alert = "alert-success";
                        ViewBag.Refresh = "False";
                        upgradeSuccess = true;
                        LegacyBackgroundMigrator.Reset();
                        break;
                    default:
                        ViewBag.Status = LegacyBackgroundMigrator.MigrationTask.Status.ToString();
                        ViewBag.Alert = "alert-warning";
                        break;
                }

                if (upgradeSuccess)
                {
                    var filter = GlobalFilters.Filters.FirstOrDefault(f => f.Instance is DbSetupFilter);
                    if (filter != null)
                    {
                        GlobalFilters.Filters.Remove(filter.Instance);
                    }
                    Database.SetInitializer(new TdIdentityDbInitializer());
                    Database.SetInitializer(new TdPushNotificationDbInitializer());
                    Startup.ConfigurePushNotifications();
                    UpdateSearchIndex();
                }
            }
            return View();
        }

        private void UpdateSearchIndex()
        {
            //TODO: duplicated in DatabaseConfig.cs, should refactor extension method or something... just not sure what the most appropriate place is
            HostingEnvironment.QueueBackgroundWorkItem(async (ct) =>
            {
                using (var ctx = new TdDomainContext(null))
                {
                    await TdSearchContext.Current.IndexManager.RunIndexMaintenanceAsync();
                    var searchItems = ctx.Tickets.Include("TicketEvents").ToSeachIndexItems();
                    await TdSearchContext.Current.IndexManager.AddItemsToIndexAsync(searchItems);
                }
            });
        }

        [HttpPost]
        [Route("create-database")]
        public async Task<ActionResult> CreateDatabase(string email, string password, string displayName)
        {
            using (var ctx = new TdDomainContext(null))
            {
                Database.SetInitializer(
                    new MigrateDatabaseToLatestVersion<TdDomainContext, Configuration>(true));
                ctx.Database.Initialize(true);
            }




            var filter = GlobalFilters.Filters.FirstOrDefault(f => f.Instance is DbSetupFilter);
            if (filter != null)
            {
                GlobalFilters.Filters.Remove(filter.Instance);
            }

            Database.SetInitializer(new TdIdentityDbInitializer());
            var existingUser = UserManager.FindByName(email);
            TicketDeskUser newUser = null;
            if (existingUser == null)
            {
                newUser = new TicketDeskUser { UserName = email, Email = email, DisplayName = displayName };
                await UserManager.CreateAsync(newUser, password);
                await UserManager.AddToRoleAsync(newUser.Id, "TdAdministrators");
               

            }
            else
            {
                //should only happen if user entered one of the demo user names when setting up the DB
                //reset the password to the one the user entered here, and set the admin role if needed
                var token = await UserManager.GeneratePasswordResetTokenAsync(existingUser.Id);
                await UserManager.ResetPasswordAsync(existingUser.Id, token, password);
                existingUser.DisplayName = displayName;
                await UserManager.UpdateAsync(existingUser);
                if (!UserManager.IsTdAdministrator(existingUser.Id))
                {
                    await UserManager.AddToRoleAsync(existingUser.Id, "TdAdministrators");
                }
            }
            Database.SetInitializer(new TdPushNotificationDbInitializer());

            Startup.ConfigurePushNotifications();
            if (newUser != null)
            {
                using (var notificationContext = new TdPushNotificationContext())
                {
                    notificationContext.SubscriberPushNotificationSettingsManager.AddSettingsForSubscriber(
                        new SubscriberNotificationSetting
                        {
                            SubscriberId = newUser.Id,
                            IsEnabled = true,
                            PushNotificationDestinations = new[]
                            {
                                new PushNotificationDestination()
                                {
                                    DestinationType = "email",
                                    DestinationAddress = newUser.Email,
                                    SubscriberName = newUser.DisplayName
                                }
                            }
                        });
                    notificationContext.SaveChanges();
                }
            }
            UpdateSearchIndex();
            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public ActionResult AzureInfo()
        {
            if (!Model.AzureInfo.HasAzureServices)
            {
                return new EmptyResult();
            }
            return PartialView("_AzureInfo", Model);

        }

        [ChildActionOnly]
        public ActionResult DatabaseInfo()
        {
            return PartialView("_DatabaseInfo", Model);
        }

        [ChildActionOnly]
        public ActionResult NewDatabase()
        {
            if (Model.DatabaseStatus.IsDatabaseReady || Model.DatabaseStatus.IsLegacyDatabase)
            {
                return new EmptyResult();
            }

TicketDesk.Web.Client/Views/FirstRunSetup/CheckUpgradeProgress.cshtml
@*
    TicketDesk - Attribution notice
    Contributor(s):

         Stephen Redd (https://github.com/stephenredd)

    This file is distributed under the terms of the Microsoft Public
    License (Ms-PL). See http://opensource.org/licenses/MS-PL
    for the complete terms of use.

    For any distribution that contains code from this file, this notice of
    attribution must remain intact, and a copy of the license must be
    provided to the recipient.
*@
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>First Run Setup</title>
    @Styles.Render("~/content/styles")
    @Scripts.Render("~/bundles/common")
    <script type="text/javascript">

        $(window).ready(function () {
            $("#log").scrollTop($("#log")[0].scrollHeight);
            var time = 3;
            if ('@ViewBag.Refresh' === 'True') {
                setInterval(function () {
                    time--;
                    $('#time').html(time);
                    if (time === 1) {
                        location.reload();
                    }
                }, 3000);
            }
        });
    </script>
</head>
<body>
    <div>
        <h1 class="text-center">TicketDesk - First-Run Setup</h1>
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Upgrading Legacy Database - Progress Report: </div>
                    <div class="panel-body">
                        <div class="alert @ViewBag.Alert">
                            <div>
                                @ViewBag.Status
                            </div>
                            @if (ViewBag.Refresh == "True")
                            {
                                <div class="small">
                                    <i class="fa fa-refresh fa-spin"></i> Refreshing in <span id="time">3</span>
                                </div>
                            }
                        </div>
                        @if (ViewBag.Status == "Completed")
                        {
                            <div class="alert alert-info">
                                Your database has been upgraded.
                                <br /><br />
                                <a href="@Url.Action("Index", "Home")" class="btn btn-success">Continue to TicketDesk</a>
                            </div>
                        }
                        @if (ViewBag.Status == "Failed" || ViewBag.Status == "Cancelled")
                        {
                            <div class="alert alert-danger">
                                Your database upgrade failed! If the failure occured while importing images, then you can probably re-try the upgrade. <br /><br />
                                If the failure occured during database conversion, the database is probably corrupt now. Please restore the database from backup and retry. The next upgrade attempt will skip any images that were previously migrated.
                                <br /><br />
                                <a href="@Url.Action("Index", "FirstRunSetup")" class="btn btn-success">Return to First-Run-Setup</a>
                            </div>
                        }
                        <div id="log" class="well" style="max-height: 400px;overflow:auto">
                            @Html.Raw(ViewBag.Messages)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

TicketDesk.Web.Client/Views/FirstRunSetup/Index.cshtml
@*
    TicketDesk - Attribution notice
    Contributor(s):

         Stephen Redd (https://github.com/stephenredd)

    This file is distributed under the terms of the Microsoft Public
    License (Ms-PL). See http://opensource.org/licenses/MS-PL
    for the complete terms of use.

    For any distribution that contains code from this file, this notice of
    attribution must remain intact, and a copy of the license must be
    provided to the recipient.
*@
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>First Run Setup</title>
    @Styles.Render("~/content/styles")
</head>
<body>
    <div>
        <h1 class="text-center">TicketDesk - First-Run Setup</h1>
      
       
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Application Insights Info</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-3">Application Insights </div>
                            <div class="col-sm-8">@(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active.DisableTelemetry? "Disabled" : "Enabled")</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                @{ Html.RenderAction("AzureInfo"); }
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">

                @{ Html.RenderAction("DatabaseInfo"); }

            </div>
        </div>
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                @{ Html.RenderAction("NewDatabase"); }
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                @{ Html.RenderAction("LegacyDatabase"); }
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                @{ Html.RenderAction("LegacySecurity"); }
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                @{ Html.RenderAction("SetupCompleteInfo"); }
            </div>
        </div>
    </div>
</body>
</html>

TicketDesk.Web.Client/Views/FirstRunSetup/_AzureInfo.cshtml
@*
    TicketDesk - Attribution notice
    Contributor(s):

         Stephen Redd (https://github.com/stephenredd)

    This file is distributed under the terms of the Microsoft Public
    License (Ms-PL). See http://opensource.org/licenses/MS-PL
    for the complete terms of use.

    For any distribution that contains code from this file, this notice of
    attribution must remain intact, and a copy of the license must be
    provided to the recipient.
*@
@model TicketDesk.Web.Client.Models.SystemInfoViewModel

<div class="panel panel-default">
    <div class="panel-heading">Azure Info</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-3">Azure WebSite</div>
            <div class="col-sm-8">@Model.AzureInfo.AzureWebSiteName</div>
        </div>
        <div class="row">
            <div class="col-sm-3">Azure Search</div>
            <div class="col-sm-8">@Model.AzureInfo.AzureSearchService</div>
        </div>
        <div class="row">
            <div class="col-sm-3">Azure Storage</div>
            <div class="col-sm-8">@Model.AzureInfo.AzureStorageService</div>
        </div>
        <div class="row">
            <div class="col-sm-3">Azure SQL</div>
            <div class="col-sm-8">@Model.AzureInfo.AzureSqlService</div>
        </div>
        
    </div>
</div>

TicketDesk.Web.Client/Views/FirstRunSetup/_DatabaseInfo.cshtml
@*
    TicketDesk - Attribution notice
    Contributor(s):

         Stephen Redd (https://github.com/stephenredd)

    This file is distributed under the terms of the Microsoft Public
    License (Ms-PL). See http://opensource.org/licenses/MS-PL
    for the complete terms of use.

    For any distribution that contains code from this file, this notice of
    attribution must remain intact, and a copy of the license must be
    provided to the recipient.
*@
@model TicketDesk.Web.Client.Models.SystemInfoViewModel
<div class="panel panel-default">
    <div class="panel-heading">Database Configuration</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-3">Server Type</div>
            <div class="col-sm-8">
                @if (Model.DatabaseInfo.IsLocalDb)
                {
                    @:LocalDb -
                }
                @Model.DatabaseInfo.DbEdition
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">Server Name</div>
            <div class="col-sm-8">@Model.DatabaseInfo.ServerName</div>
        </div>
        @if (!string.IsNullOrEmpty(Model.DatabaseInfo.SqlInstance))
        {
            <div class="row">
                <div class="col-sm-3">Instance Name</div>
                <div class="col-sm-8">@Model.DatabaseInfo.SqlInstance</div>
            </div>
        }
        <div class="row">
            <div class="col-sm-3">
                Database @(Model.DatabaseInfo.IsFileDatabase ? "Location" : "Name")
            </div>
            <div class="col-sm-8">@Model.DatabaseInfo.DatabaseName</div>
        </div>
        <div class="row">
            <div class="col-sm-3">Database Type</div>
            <div class="col-sm-8 ">
                @(Model.DatabaseInfo.IsFileDatabase ? "File Database" : "SQL Catalog")

            </div>
        </div>
       
    </div>
    @if (Model.DatabaseStatus.IsDatabaseReady)
    {
        <div class="panel-footer text-center text-success">
           
                Your database is configured and ready to use!
        </div>
    }
</div>

TicketDesk.Web.Client/Views/FirstRunSetup/_LegacyDatabase.cshtml
@*
    TicketDesk - Attribution notice
    Contributor(s):

         Stephen Redd (https://github.com/stephenredd)

    This file is distributed under the terms of the Microsoft Public
    License (Ms-PL). See http://opensource.org/licenses/MS-PL
    for the complete terms of use.

    For any distribution that contains code from this file, this notice of
    attribution must remain intact, and a copy of the license must be
    provided to the recipient.
*@
@model TicketDesk.Web.Client.Models.SystemInfoViewModel
<div class="panel panel-default">
    <div class="panel-heading">Upgrade Legacy Database</div>
    <div class="panel-body">

        <p>
            TicketDesk has detected an existing database for TicketDesk version 2.1x.
        </p>
        <p class="alert alert-danger">
            This cannot be undone! Please make sure you have a database backup.
        </p>
        <p>
            Would you like to Upgrade this database for use with TicketDesk 2.5?
        </p>
        @Html.ActionLink("Upgrade Database", "UpgradeDatabase", null, new { @class = "btn btn-primary" })

    </div>
</div>

TicketDesk.Web.Client/Views/FirstRunSetup/_LegacySecurity.cshtml
@*
    TicketDesk - Attribution notice
    Contributor(s):

         Stephen Redd (https://github.com/stephenredd)

    This file is distributed under the terms of the Microsoft Public
    License (Ms-PL). See http://opensource.org/licenses/MS-PL
    for the complete terms of use.

    For any distribution that contains code from this file, this notice of
    attribution must remain intact, and a copy of the license must be
    provided to the recipient.
*@
@model TicketDesk.Web.Client.Models.SystemInfoViewModel
<div class="panel panel-default">
    <div class="panel-heading">Migrate Legacy Security</div>
    <div class="panel-body">
        <p>
            TicketDesk has detected legacy membership objects. TicketDesk can attempt to migrate the user accounts for use with TicketDesk 2.5.
        </p>
        <p class="alert alert-danger">
            This cannot be undone! Please make sure you have a database backup.
        </p>
        <p class="alert alert-info">
            After the migration, users will login using the email address associated with their accounts.
        </p>
        <p>
            Would you like to migrate users to the new identity system for TicketDesk 2.5?
        </p>
        @Html.ActionLink("Migrate Users", "LegacyMigration", null, new { @class = "btn btn-primary" })
    </div>
</div>

TicketDesk.Web.Client/Views/FirstRunSetup/_NewDatabase.cshtml
@*
    TicketDesk - Attribution notice
    Contributor(s):

         Stephen Redd (https://github.com/stephenredd)

    This file is distributed under the terms of the Microsoft Public
    License (Ms-PL). See http://opensource.org/licenses/MS-PL
    for the complete terms of use.

    For any distribution that contains code from this file, this notice of
    attribution must remain intact, and a copy of the license must be
    provided to the recipient.
*@
@model TicketDesk.Web.Client.Models.SystemInfoViewModel
@using (Html.BeginForm("CreateDatabase", "FirstRunSetup", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-heading">Create Database</div>
        <div class="panel-body">
            @if (ViewBag.WarnNotAnAzureDb ?? false)
            {
                <p class="alert alert-warning">
                    TicketDesk appears to be running as a Microsoft Azure WebSite, but the database is not
                    configured for Azure SQL Server. Azure SQL is not required, but please make sure the configured SQL Server
                    connection information is correct and accessible from your Azure WebSite before continuing.
                </p>
            }
            @if (ViewBag.ErrorAzureDbDoesNotExist ?? false)
            {
                <p class="alert alert-danger">
                    TicketDesk appears to be running as a Microsoft Azure WebSite and the database appears
                    to be configured for Azure SQL Server, but the configured database does not appear to have been provisioned in Azure SQL yet.
                    <br/><br/>
                    For security reasons, TicketDesk cannot provision Azure SQL databases automatically. You must provision the Azure SQL
                    Database using Azure Powershell or through the online Azure Management Portal. <br/><br/>
                    Once the database has been provisioned, this utility can create the TicketDesk objects in the database for you automatically.
                </p>
            }
            @if (!(ViewBag.ErrorAzureDbDoesNotExist ?? false))
            {
                <div class="col-lg-7 col-md-8 col-sm-12">
                    <p class="alert alert-warning">
                        Enter credentials for the initial administrator user account.
                    </p>


                    <div class="form-group">
                        <label class="col-sm-3 control-label">Email</label>
                        <div class="col-sm-9">
                            @Html.TextBox("Email", null, new {type = "email", @class = "form-control", required = "required"})
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Password</label>
                        <div class="col-sm-9">
                            @Html.TextBox("Password", null, new {type = "password", @class = "form-control", required = "required" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Display Name</label>
                        <div class="col-sm-9">
                            @Html.TextBox("DisplayName", null, new {@class = "form-control", required = "required" })
                        </div>
                    </div>


                </div>
            }
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-success" tabindex="10">Create Database</button>
        </div>
    </div>
}

TicketDesk.Web.Client/Views/FirstRunSetup/_SetupCompleteInfo.cshtml
@*
    TicketDesk - Attribution notice
    Contributor(s):

         Stephen Redd (https://github.com/stephenredd)

    This file is distributed under the terms of the Microsoft Public
    License (Ms-PL). See http://opensource.org/licenses/MS-PL
    for the complete terms of use.

    For any distribution that contains code from this file, this notice of
    attribution must remain intact, and a copy of the license must be
    provided to the recipient.
*@
@model TicketDesk.Web.Client.Models.SystemInfoViewModel
<div class="panel panel-success">
    <div class="panel-heading">Setup Complete</div>
    <div class="panel-body">
        <p>
            Your TicketDesk instance appears to be all setup and ready to use.
        </p>
        <p class="alert alert-danger">
            For your security, please disable this first-run-setup utility.<br /><br />
            <span class="text-info">
                Open web.config from the root of the application in a text editor. Locate the &lt;appSettings&gt; section, then change the value of ticketdesk:SetupEnabled to false. If runing as an Azure WebSite, you can also set this value in your website settings with the online Azure Management Portal.
            </span>
        </p>
        
        @Html.ActionLink("Go to TicketDesk", "Index", "Home", null, new {@class = "btn btn-success"})


    </div>

</div>